[build]
builder = "nixpacks"
buildCommand = "pip install -r requirements.txt"

[deploy]
startCommand = "uvicorn app:app --host 0.0.0.0 --port 8080"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[[services]]
name = "web"
command = "gunicorn app:app --workers 1 --worker-class uvicorn.workers.UvicornWorker"

[[services]]
name = "worker"
command = "python scripts/persona_cache_generator.py" 